<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class CostElementTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        if(env('DB_DRIVER') == 'mysql')
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        if(env('DB_DRIVER') == 'mysql')
            DB::table('cost_elements')->truncate();

        DB::table('cost_elements')->insert(array(
            0 => array(
                'level'       => '1',
                'name'        => 'Tunel de Lavado Automatico',
                'slug'        => 'TLA',
                'required'    => 'Todas las paradas originan costes por penalizacion',
                'quantity'    => 1,
                'cost'        => '',
                'intensity'   => '',
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => null,
                'sub_system_id' => null
            ),
            1 => array(
                'level'       => '1',
                'name'        => 'Sistema de Aire Comprimido',
                'slug'        => 'SAC',
                'required'    => 'Todas las paradas originan costes por penalizacion',
                'quantity'    => 1,
                'cost'        => '',
                'intensity'   => '',
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => null,
                'sub_system_id' => null
            ),
            2 => array(
                'level'       => '1',
                'name'        => 'Maquina Dispensadora de Diesel',
                'slug'        => 'MDD',
                'required'    => 'Todas las paradas originan costes por penalizacion',
                'quantity'    => 1,
                'cost'        => '',
                'intensity'   => '',
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => null,
                'sub_system_id' => null
            ),
            3 => array(
                'level'       => '1',
                'name'        => 'Sistema Hidroneumatico',
                'slug'        => 'SHI',
                'required'    => 'Todas las paradas originan costes por penalizacion',
                'quantity'    => 1,
                'cost'        => '',
                'intensity'   => '',
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => null,
                'sub_system_id' => null
            ),
            4 => array(
                'level'       => '1',
                'name'        => 'Puente Grua',
                'slug'        => 'PGR',
                'required'    => 'Todas las paradas originan costes por penalizacion',
                'quantity'    => 1,
                'cost'        => '',
                'intensity'   => '',
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => null,
                'sub_system_id' => null
            ),
            5 => array(
                'level'       => '2',
                'name'        => 'Sistemas de Cepillos Giratorios',
                'slug'        => 'SCG',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 1,
                'sub_system_id' => null
            ),
            6 => array(
                'level'       => '2',
                'name'        => 'Tablero de control electronico',
                'slug'        => 'TCE',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 795,
                'intensity'   => 3,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 2,
                'sub_system_id' => null
            ),
            7 => array(
                'level'       => '2',
                'name'        => 'Sistema dispensador de champu',
                'slug'        => 'SDC',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 3,
                'sub_system_id' => null
            ),
            8 => array(
                'level'       => '2',
                'name'        => 'Sistema de bombeo',
                'slug'        => 'SDB',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 4,
                'sub_system_id' => null
            ),
            9 => array(
                'level'       => '3',
                'name'        => 'Compresores',
                'slug'        => 'COM1',
                'required'    => '',
                'quantity'    => 2,
                'cost'        => 20500,
                'intensity'   => 4,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 5,
                'sub_system_id' => null
            ),
            10 => array(
                'level'       => '3',
                'name'        => 'Sistema de filtrado',
                'slug'        => 'SDF',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 6,
                'sub_system_id' => null
            ),
            11 => array(
                'level'       => '3',
                'name'        => 'Sistema de transmision',
                'slug'        => 'SDT',
                'required'    => '',
                'quantity'    => 2,
                'cost'        => 7000,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 7,
                'sub_system_id' => null
            ),
            12 => array(
                'level'       => '3',
                'name'        => 'Sistema de refrigeracion y condensado',
                'slug'        => 'SRC',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 2000,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 8,
                'sub_system_id' => null
            ),
            13 => array(
                'level'       => '4',
                'name'        => 'Tablero de control',
                'slug'        => 'TDC1',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 5000,
                'intensity'   => 3,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 9,
                'sub_system_id' => null
            ),
            14 => array(
                'level'       => '4',
                'name'        => 'Sistema dispensador',
                'slug'        => 'SDI',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 10,
                'sub_system_id' => null
            ),
            15 => array(
                'level'       => '4',
                'name'        => 'Linea de succion',
                'slug'        => 'LDS',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 11,
                'sub_system_id' => null
            ),
            16 => array(
                'level'       => '4',
                'name'        => 'Tanque de combustible',
                'slug'        => 'TCB',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 5000,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 12,
                'sub_system_id' => null
            ),
            17 => array(
                'level'       => '4',
                'name'        => 'Sistema de bombeo',
                'slug'        => 'SB1',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 4000,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 13,
                'sub_system_id' => null
            ),
            18 => array(
                'level'       => '4',
                'name'        => 'Sistema de filtrado',
                'slug'        => 'SFI',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 3000,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 14,
                'sub_system_id' => null
            ),
            19 => array(
                'level'       => '5',
                'name'        => 'Tablero de Control',
                'slug'        => 'TDC2',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 15,
                'sub_system_id' => null
            ),
            20 => array(
                'level'       => '5',
                'name'        => 'Sistema de bombeo',
                'slug'        => 'SB2',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 16,
                'sub_system_id' => null
            ),
            21 => array(
                'level'       => '5',
                'name'        => 'Sistema de purga',
                'slug'        => 'SDP',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 2000,
                'intensity'   => 3,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 17,
                'sub_system_id' => null
            ),
            22  => array(
                'level'       => '5',
                'name'        => 'Compresor',
                'slug'        => 'COM2',
                'required'    => '',
                'quantity'    => 2,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 18,
                'sub_system_id' => null
            ),
            23 => array(
                'level'       => '5',
                'name'        => 'Sistema de tuberias',
                'slug'        => 'STU',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 19,
                'sub_system_id' => null
            ),
            24 => array(
                'level'       => '5',
                'name'        => 'Sistema de valvulas e impelente',
                'slug'        => 'SVI',
                'required'    => '',
                'quantity'    => 2,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 20,
                'sub_system_id' => null
            ),
            25 => array(
                'level'       => '5',
                'name'        => 'Sistema electrico',
                'slug'        => 'SE1',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 21,
                'sub_system_id' => null
            ),
            26 => array(
                'level'       => '5',
                'name'        => 'Tanque de presion',
                'slug'        => 'TDP',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 3000,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => null,
                'sub_system_id' => null
            ),
            27 => array(
                'level'       => '5',
                'name'        => 'Instrumentos de control',
                'slug'        => 'IDC',
                'required'    => '',
                'quantity'    => 2,
                'cost'        => 0,
                'intensity'   => 0,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 22,
                'sub_system_id' => null
            ),
            28 => array(
                'level'       => '6',
                'name'        => 'Elemento de elevacion',
                'slug'        => 'EDE',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 1000,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 23,
                'sub_system_id' => null
            ),
            29 => array(
                'level'       => '6',
                'name'        => 'Carro',
                'slug'        => 'CRR',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 5000,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 24,
                'sub_system_id' => null
            ),
            30 => array(
                'level'       => '6',
                'name'        => 'Puente',
                'slug'        => 'PTE',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 3000,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 25,
                'sub_system_id' => null
            ),
            31 => array(
                'level'       => '6',
                'name'        => 'Sistema electrico',
                'slug'        => 'SE2',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 2500,
                'intensity'   => 4,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 26,
                'sub_system_id' => null
            ),
            32 => array(
                'level'       => '6',
                'name'        => 'Sistema de testeros',
                'slug'        => 'SDT',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 2000,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 27,
                'sub_system_id' => null
            ),
            33 => array(
                'level'       => '7',
                'name'        => 'Cepillos y eje',
                'slug'        => 'CYE',
                'required'    => '',
                'quantity'    => 4,
                'cost'        => 1200,
                'intensity'   => 8,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 1,
                'sub_system_id' => 1
            ),
            34 => array(
                'level'       => '7',
                'name'        => 'Sistema de desplazamineto de cepillos',
                'slug'        => 'SDC',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 2000,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 1,
                'sub_system_id' => 2
            ),
            35 => array(
                'level'       => '8',
                'name'        => 'Membrana',
                'slug'        => 'MBR',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 300,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 3,
                'sub_system_id' => 4
            ),
            36 => array(
                'level'       => '8',
                'name'        => 'Rodamientos',
                'slug'        => 'RDS',
                'required'    => '',
                'quantity'    => 4,
                'cost'        => 100,
                'intensity'   => 3,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 3,
                'sub_system_id' => 5
            ),
            37 => array(
                'level'       => '10',
                'name'        => 'Filtro de aire',
                'slug'        => 'FDA',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 150,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 6,
                'sub_system_id' => 10
            ),
            38 => array(
                'level'       => '10',
                'name'        => 'Filtro de aspiracion',
                'slug'        => 'FAS',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 200,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 6,
                'sub_system_id' => 11
            ),
            39 => array(
                'level'       => '10',
                'name'        => 'Filtro separador de aceite',
                'slug'        => 'FSA',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 300,
                'intensity'   => 3,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 6,
                'sub_system_id' => 12
            ),
            40 => array(
                'level'       => '9',
                'name'        => 'Chumaceras',
                'slug'        => 'CHU',
                'required'    => '',
                'quantity'    => 4,
                'cost'        => 400,
                'intensity'   => 4,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 7,
                'sub_system_id' => 13
            ),
            41 => array(
                'level'       => '9',
                'name'        => 'Sellos',
                'slug'        => 'SLL',
                'required'    => '',
                'quantity'    => 2,
                'cost'        => 200,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => null,
                'sub_system_id' => null
            ),
            42 => array(
                'level'       => '11',
                'name'        => 'Carcasa del surtidor',
                'slug'        => 'CDS',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 90,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 10,
                'sub_system_id' => 15
            ),
            43 => array(
                'level'       => '11',
                'name'        => 'Boquillas surtidoras',
                'slug'        => 'BSU',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 85,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 10,
                'sub_system_id' => 16
            ),
            44 => array(
                'level'       => '12',
                'name'        => 'Colador',
                'slug'        => 'CDR',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 100,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 11,
                'sub_system_id' => 17
            ),
            45 => array(
                'level'       => '12',
                'name'        => 'Malla',
                'slug'        => 'MLL',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 100,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 11,
                'sub_system_id' => 18
            ),
            46 => array(
                'level'       => '13',
                'name'        => 'Terminales de conexion',
                'slug'        => 'TDC',
                'required'    => '',
                'quantity'    => 22,
                'cost'        => 20,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 15,
                'sub_system_id' => 22
            ),
            47 => array(
                'level'       => '13',
                'name'        => 'Contactores,reles y solenoides',
                'slug'        => 'CRS',
                'required'    => '',
                'quantity'    => 2,
                'cost'        => 30,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 15,
                'sub_system_id' => 23
            ),
            48 => array(
                'level'       => '14',
                'name'        => 'Anclaje de las bombas',
                'slug'        => 'ADB',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 30,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 16,
                'sub_system_id' => 24
            ),
            49 => array(
                'level'       => '15',
                'name'        => 'Correas',
                'slug'        => 'CRR',
                'required'    => '',
                'quantity'    => 2,
                'cost'        => 00,
                'intensity'   => 5,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 18,
                'sub_system_id' => 26
            ),
            50 => array(
                'level'       => '16',
                'name'        => 'Uniones',
                'slug'        => 'UNI',
                'required'    => '',
                'quantity'    => 6,
                'cost'        => 50,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 19,
                'sub_system_id' => 27
            ),
            51 => array(
                'level'       => '16',
                'name'        => 'Valvulas de drenaje, check y compuerta',
                'slug'        => 'VDCC',
                'required'    => '',
                'quantity'    => 10,
                'cost'        => 95,
                'intensity'   => 3,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => null,
                'sub_system_id' => null
            ),
            52 => array(
                'level'       => '17',
                'name'        => 'Sellos mecanicos',
                'slug'        => 'SMC',
                'required'    => '',
                'quantity'    => 10,
                'cost'        => 5,
                'intensity'   => 1,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 20,
                'sub_system_id' => 28
            ),
            53 => array(
                'level'       => '17',
                'name'        => 'Rodamiento',
                'slug'        => 'RDM',
                'required'    => '',
                'quantity'    => 10,
                'cost'        => 135,
                'intensity'   => 4,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 20,
                'sub_system_id' => 29
            ),
            54 => array(
                'level'       => '18',
                'name'        => 'Bobinas',
                'slug'        => 'BOB',
                'required'    => '',
                'quantity'    => 1,
                'cost'        => 90,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 21,
                'sub_system_id' => 30
            ),
            55 => array(
                'level'       => '19',
                'name'        => 'Presostatos',
                'slug'        => 'PST',
                'required'    => '',
                'quantity'    => 6,
                'cost'        => 30,
                'intensity'   => 2,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 22,
                'sub_system_id' => 31
            ),
            56 => array(
                'level'       => '19',
                'name'        => 'Manometros',
                'slug'        => 'MNM',
                'required'    => '',
                'quantity'    => 4,
                'cost'        => 22,
                'intensity'   => 3,
                'created_at' => date('Y-m-d H:m:s'),
                'updated_at' => date('Y-m-d H:m:s'),
                'system_id'  => 32,
                'sub_system_id' => 22
            )
        ));

        if(env('DB_DRIVER') == 'mysql')
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
